version: '3.7'

services:
  app:
    build:
      context: ./
      args:
        __SECRET__TOKEN: '${TOKEN:-ThisTokenIsNotSoSecretChangeIt}'
        SERVER_PORT: '${VPORT:-3000}'
    image: 'khemlabs/tracking-server:${TAG:-latest}'
    volumes:
      - app:/app
      # - modules:/app/node_modules
      - data:/data
    restart: always
    environment:
      __SECRET__TOKEN: '${TOKEN:-ThisTokenIsNotSoSecretChangeIt}'
      SERVER_PORT: '${VPORT:-3000}'
      VIRTUAL_HOST: '${VHOST}'
      VIRTUAL_PORT: '${VPORT:-3000}'
      LETSENCRYPT_HOST: '${VHOST}'
      LETSENCRYPT_EMAIL: '${EMAIL}'      

volumes:
  app:
  # modules:
  data:

networks:
  default:
    external:
      name: tracking-network